### ISSUE TITLE
Terrain and sodaracer are not visible - black screen with simulator menu/stats only

### ISSUE THREAD

**Issue by daia99** [CarperAI/ELM#10]
Outcome when running `python -m framework_simulator` in sodaracer_env in my current environment.

Tested on both sodaracer json files in `example_bodies`, and on branches main, build-lego. I'm using Ubuntu 20.04, with Python 3.8.13.

Has anyone tried running this with a different environment setup in the case that you can see the sodaracer agent?

![image](https://user-images.githubusercontent.com/33094749/193633706-a89fa260-88a4-46b9-b73c-734e553e7af3.png)

**Comment by dmahan93** [comment]
can you scroll out? After scrolling out I can see everything 
![image](https://user-images.githubusercontent.com/44207705/193676322-b7ad5626-65b3-4638-91b8-6d688fa4deef.png)

**Comment by daia99** [comment]
Can confirm that dragging the right mouse button to pan, and using the scroll wheel adjusts the view correctly.

Thanks for sharing this, closing now since this is resolved.
